baseURL = 'https://www.jantz.website/'
languageCode = 'en-US'
title = 'Ethan Jantz'
enableGitInfo = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Ideas"
    url = "/ideas/"
    weight = 2

  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 3
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"