baseURL = 'https://www.jantz.website/'
languageCode = 'en-US'
title = 'Ethan Jantz'
enableGitInfo = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Ideas"
    url = "/ideas/"
    weight = 3

  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 4

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
